### PR TITLE
Fix crash in `after_place_node` when sign is already in pole "mode"

### LINKED ISSUE #158: Runtime error from mod 'signs_api' in callback item_OnPlace(): "Unknown node: streets:sign_triangle_t_polemount_polemount"
```lua
2024-02-09 18:27:02: ERROR[Main]: ServerError: AsyncErr: Lua: Runtime error from mod 'signs_api' in callback item_OnPlace(): "Unknown node: streets:sign_triangle_t_polemount_polemount"
2024-02-09 18:27:02: ERROR[Main]: stack traceback:
2024-02-09 18:27:02: ERROR[Main]: 	[C]: in function '__index'
2024-02-09 18:27:02: ERROR[Main]: 	...minetest/minetest-5.8.0/bin/../builtin/common/item_s.lua:229: in function <...minetest/minetest-5.8.0/bin/../builtin/common/item_s.lua:228>
2024-02-09 18:27:02: ERROR[Main]: 	[C]: in function 'set_node'
2024-02-09 18:27:02: ERROR[Main]: 	...ik/minetest/minetest-5.8.0/bin/../mods/streets/signs.lua:706: in function 'after_place_node'
2024-02-09 18:27:02: ERROR[Main]: 	...nik/minetest/minetest-5.8.0/bin/../builtin/game/item.lua:272: in function 'on_place'
2024-02-09 18:27:02: ERROR[Main]: 	...est-5.8.0/bin/../mods/replacer/replacer/api/replacer.lua:138: in function <...est-5.8.0/bin/../mods/replacer/replacer/api/replacer.lua:64>
```

Lonny tried to replace a street sign, can't reproduce (yet).

### PR DESCRIPTION
**Pull request by Niklp09**
Fixes https://github.com/Archtec-io/bugtracker/issues/158

### CODE REVIEW

File: signs.lua [hunk 1]
```diff
@@ -701,7 +701,8 @@ streets.register_sign = function(name, def)
             if (param2 >= 0 and param2 <= 4)  and exact_point then
                 local component = (param2 == 0 or param2 == 2) and "z" or "x"
                 behind_pos[component] = behind_pos[component] + (param2 <= 1 and 1 or -1)
-                if math.abs(pos[component] - exact_point[component]) >= .75 then
+                local is_pole = string.sub(node.name, #node.name - 9, #node.name)
+                if math.abs(pos[component] - exact_point[component]) >= .75 and is_pole ~= "_polemount" then
```
Comment (Thomas--S) [inline signs.lua]:
```suggestion
                if math.abs(pos[component] - exact_point[component]) >= .75 and minetest.registered_nodes[node.name .. "_polemount"] then
```

Unfortunately, I can't reproduce this problem. But wouldn't it be more elegant to check if the node is registered?
